/**
 * Loader generated by glad 2.0.8 on Sat Feb  1 22:47:13 2025
 *
 * SPDX-License-Identifier: (WTFPL OR CC0-1.0) AND Apache-2.0
 *
 * splitted into separate headers: define (macros,values), header, loader and source
 *      by Oleg'Ease'Kharchuk
 */
#ifndef SON8_OVERGLAD_GLAD_SON8_DEFINE_H
#define SON8_OVERGLAD_GLAD_SON8_DEFINE_H

#include <glad/son8/define/values.h>

#include <glad/son8/define/macros.h>

#endif//SON8_OVERGLAD_GLAD_SON8_DEFINE_H
